#!/bin/bash

# Restore CachyOS repositories after Omarchy overwrites /etc/pacman.conf.

OMARCHY_PATH=${OMARCHY_PATH:-$HOME/.local/share/omarchy}

# shellcheck disable=SC1091
source "$OMARCHY_PATH/install/personal/helpers/cachyos-pacman-repos.sh"

omarchy_cachyos_pacman_repos_ensure
